### ISSUE TITLE
The Mozilla Public License is a per-file license

### ISSUE THREAD

**Issue by TechnikEmpire** [cloudveiltech/CitadelCore#2]
Just wanted to let you guys know that the MPL is a per-file license. You've added files that don't have an MPL license header in front of them, and so they're technically unlicensed to the public, or at least using them is legally questionable (for outsiders) which would ward off serious users. What I mean to say is, it's your exclusive copyright and is not offered under any license. I don't care personally because the additions are of no use to me, I'm just trying to help you guys out. See Mozilla's official notes here:

https://www.mozilla.org/en-US/MPL/

> Please use the appropriate header text at the top of each file.

Also see:

https://www.mozilla.org/en-US/MPL/2.0/FAQ/

> Q4: I want to use the Mozilla Public License for software that I have written. What do I have to do?
> To apply the Mozilla Public License to software that you have written, add the header from Exhibit A of the license to each source code file in your project.

Also note however that because it is per-file, the great news is that these newly added files can be licensed basically however you'd like (as long as it's compatible I guess with MPL), or kept entirely proprietary. That's the beauty of the MPL. Forces the original work to stay open and benefit all, but enables proprietary competitive advantage building.

**Comment by TechnikEmpire** [comment]
Note also that the license changed from LGPL to MPL2 in CitadelCore.Windows, so same thing goes there now too. That's thanks to WinDivertSharp being created as a separate project, which you guys have already forked.

**Comment by dkwiebe** [comment]
Thanks for pointing this out.  I'll make sure it's corrected.
